name: jg
favicon: null
layout_spectrum: 0.950930182589218
typography_spectrum: 0.4400322812143713
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7807615520432591
  lightness: 0.9797308635897934
  saturation: 0.5856640615966171
  rhythmicContrast: 0.7705794277135283
purpose: []
